# Lab 1: Numpy features

In [116]:
import pandas as pd
import numpy as np

## Creating arrays

In [117]:
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a=np.array([1, 2, 3, 4], dtype=np.float32)
a

array([1., 2., 3., 4.], dtype=float32)

In [119]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
np.ones(9, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [121]:
np.zeros((2, 4), dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [122]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [123]:
np.random.normal(1,1,(4,3))

array([[ 0.20566191, -0.0265069 , -1.0884995 ],
       [-1.05790644,  1.14880397,  2.37415709],
       [ 4.55844854,  1.51635305,  0.62388709],
       [ 0.16853329,  0.93057646,  1.68304028]])

In [124]:
np.random.randint(0, 100, (4, 4))

array([[10, 48, 16, 90],
       [56, 13, 15, 75],
       [55, 18, 82, 63],
       [64, 53, 11, 68]])

In [125]:
np.empty(3)

array([0.25, 0.5 , 0.75])

## Working with dimentions

In [126]:
b=np.random.randint(0, 10, (4,4,3))
a=np.array([1, 2, 3, 4, 5], dtype='float')
b.ndim, a.ndim

(3, 1)

In [127]:
b.shape, a.shape

((4, 4, 3), (5,))

In [128]:
b.size, a.size

(48, 5)

In [129]:
b.dtype, a.dtype

(dtype('int32'), dtype('float64'))

In [130]:
b.nbytes, a.nbytes

(192, 40)

In [131]:
b.itemsize, a.itemsize

(4, 8)

## Indexing and slicing

In [132]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [133]:
a[1],a[4],a[-3]

(1, 4, 4)

In [134]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
b[1,1],b[1,-2]

(5, 5)

In [136]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [137]:
a[0:4:1], a[5::-2]

(array([0, 1, 2, 3]), array([5, 3, 1]))

## Referencing and copying

In [138]:
c = b[:2,:2]
c

array([[1, 2],
       [4, 5]])

In [139]:
c[0,0]=10
c,b

(array([[10,  2],
        [ 4,  5]]),
 array([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]))

In [140]:
d = b[:2,:2].copy()
d

array([[10,  2],
       [ 4,  5]])

In [141]:
c[0,0]=100
c,d

(array([[100,   2],
        [  4,   5]]),
 array([[10,  2],
        [ 4,  5]]))

## Operations

In [142]:
a=np.ones(4)
a+3, a*2, (3*a+1)**2,a/2,-a


(array([4., 4., 4., 4.]),
 array([2., 2., 2., 2.]),
 array([16., 16., 16., 16.]),
 array([0.5, 0.5, 0.5, 0.5]),
 array([-1., -1., -1., -1.]))

In [143]:
np.multiply.reduce(a)

1.0

In [144]:
np.add.accumulate(a)

array([1., 2., 3., 4.])

In [145]:
а = np.arange(1, 10)
np.multiply.outer(а, а)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

## Describing data

In [146]:
data = pd.read_csv('iris.csv')
petal = np.array(data['petal_length'])
petal

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [147]:
petal.max()

6.9

In [148]:
petal.min()

1.0

In [149]:
petal.mean()

3.758666666666666

In [150]:
np.median(petal)

4.35

In [151]:
np.percentile(petal,25)

1.6

In [152]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [153]:
data.shape

(150, 5)