# Lab 1: Numpy features

In [1]:
import pandas as pd
import numpy as np

## Creating arrays

In [2]:
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a=np.array([1, 2, 3, 4], dtype=np.float32)
a

array([1., 2., 3., 4.], dtype=float32)

In [4]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
np.ones(9, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.zeros((2, 4), dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [7]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.normal(1, 1, (4,3))

array([[0.62200848, 0.65887926, 1.5974831 ],
       [0.08609649, 2.39736309, 2.39520486],
       [1.27722964, 1.12653437, 0.76643464],
       [2.36389424, 1.36393005, 1.03676633]])

In [9]:
np.random.randint(0, 100, (4, 4))

array([[15, 29, 90, 71],
       [ 2, 14, 18, 67],
       [28, 44, 53, 90],
       [55, 92, 82, 69]])

In [10]:
np.empty(3)

array([0.00000000e+000, 6.95268442e-310, 6.95268442e-310])

## Working with dimentions

In [11]:
b=np.random.randint(0, 10, (4,4,3))
a=np.array([1, 2, 3, 4, 5], dtype='float')
b.ndim, a.ndim

(3, 1)

In [12]:
b.shape, a.shape

((4, 4, 3), (5,))

In [13]:
b.size, a.size

(48, 5)

In [14]:
b.dtype, a.dtype

(dtype('int32'), dtype('float64'))

In [15]:
b.nbytes, a.nbytes

(192, 40)

In [16]:
b.itemsize, a.itemsize

(4, 8)

## Indexing and slicing

In [17]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
a[1],a[4],a[-3]

(1, 4, 4)

In [19]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b[::2,:2:]

array([[1, 2],
       [7, 8]])

In [20]:
b[1,1],b[1,-2]

(5, 5)

In [21]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
a[0:4:1], a[5::-2]

(array([0, 1, 2, 3]), array([5, 3, 1]))

## Referencing and copying

In [23]:
c = b[:2,:2]
c

array([[1, 2],
       [4, 5]])

In [24]:
c[0,0]=10
c,b

(array([[10,  2],
        [ 4,  5]]),
 array([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]))

In [25]:
d = b[:2,:2].copy()
d

array([[10,  2],
       [ 4,  5]])

In [26]:
c[0,0]=100
c,d

(array([[100,   2],
        [  4,   5]]),
 array([[10,  2],
        [ 4,  5]]))

## Operations

In [27]:
a=np.ones(4)
a+3, a*2, (3*a+1)**2,a/2,-a


(array([4., 4., 4., 4.]),
 array([2., 2., 2., 2.]),
 array([16., 16., 16., 16.]),
 array([0.5, 0.5, 0.5, 0.5]),
 array([-1., -1., -1., -1.]))

In [28]:
np.multiply.reduce(a)

1.0

In [29]:
np.add.accumulate(a)

array([1., 2., 3., 4.])

In [30]:
а = np.arange(1, 10)
np.multiply.outer(а, а)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

## Describing data

In [31]:
data = pd.read_csv("../data/iris.csv")
petal = np.array(data["petal_length"])
petal

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [32]:
petal.max()

6.9

In [33]:
petal.min()

1.0

In [34]:
petal.mean()

3.758666666666666

In [35]:
np.median(petal)

4.35

In [36]:
np.percentile(petal,25)

1.6

In [37]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [38]:
data.shape

(150, 5)